### ISSUE TITLE
Employ test coverage analysis tool

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse/passage#16]
There a some free [GitHub-resident](https://github.com/marketplace) tools that collect test coverage reports, analyse 'em and summarise the results in a form you can instantly grasp the issue from. For example [CodeCov](https://github.com/marketplace/codecov).

Cosider installing one of these guys for the sake of product quality.

**Comment by ruspl-afed** [comment]
Please submit a bugzilla record and so on as we did for "Codacy"

**Comment by eparovyshnaya** [comment]
Done: [552449](https://bugs.eclipse.org/bugs/show_bug.cgi?id=552449). @ruspl-afed, you can follow as you are added to CC list.

**Comment by ruspl-afed** [comment]
Well, with re-configuration it shows 8% coverage now, looks much better than before
